version: '3.8'

services:
  trino:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - trino-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: trino_db_event_listener
      POSTGRES_USER: trino_user
      POSTGRES_PASSWORD: trino_password
    ports:
      - "5455:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - trino-network

networks:
  trino-network:
    driver: bridge

volumes:
  postgres-data: